// Top 100 car/truck manufacturers most commonly seen at car shows
export const carManufacturers = [
  "AC",
  "Acura",
  "Alfa Romeo",
  "AMC",
  "Aston Martin",
  "Auburn",
  "Audi",
  "Austin-Healey",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroën",
  "Cord",
  "Datsun",
  "DeLorean",
  "DeSoto",
  "Dodge",
  "Duesenberg",
  "Eagle",
  "Edsel",
  "Ferrari",
  "Fiat",
  "Fisker",
  "Ford",
  "Genesis",
  "GMC",
  "Honda",
  "Hudson",
  "Hummer",
  "Hyundai",
  "Infiniti",
  "International Harvester",
  "Isuzu",
  "Jaguar",
  "Jeep",
  "Jensen",
  "Kaiser",
  "Kia",
  "Lamborghini",
  "Lancia",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Lotus",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "Mercury",
  "MG",
  "Mini",
  "Mitsubishi",
  "Morgan",
  "Nash",
  "Nissan",
  "Oldsmobile",
  "Opel",
  "Packard",
  "Pagani",
  "Pantera",
  "Peugeot",
  "Plymouth",
  "Pontiac",
  "Porsche",
  "Ram",
  "Renault",
  "Rivian",
  "Rolls-Royce",
  "Saab",
  "Saturn",
  "Scion",
  "Shelby",
  "Studebaker",
  "Subaru",
  "Sunbeam",
  "Suzuki",
  "Tesla",
  "Toyota",
  "Triumph",
  "Tucker",
  "TVR",
  "Volkswagen",
  "Volvo",
  "Willys",
  "Other",
];

// Comprehensive list of motorcycle manufacturers
export const motorcycleManufacturers = [
  "Aprilia",
  "Arch Motorcycle",
  "Benelli",
  "Beta",
  "Bimota",
  "BMW",
  "Boss Hoss",
  "Britten",
  "Buell",
  "Cagiva",
  "Can-Am",
  "CFMoto",
  "Confederate",
  "Ducati",
  "Energica",
  "GasGas",
  "Harley-Davidson",
  "Hero",
  "Honda",
  "Husqvarna",
  "Hyosung",
  "Indian",
  "Jawa",
  "Kawasaki",
  "KTM",
  "Kymco",
  "Laverda",
  "LiveWire",
  "Moto Guzzi",
  "Moto Morini",
  "MV Agusta",
  "Norton",
  "Piaggio",
  "Polaris",
  "Royal Enfield",
  "Sherco",
  "Suzuki",
  "SWM",
  "Triumph",
  "Ural",
  "Vespa",
  "Victory",
  "Yamaha",
  "Zero",
];

// Vehicle classes based on vehicle type
export const vehicleClasses = {
  car: [
    "Best Classic Stock Car (1900-1970)",
    "Best Classic Stock Car (1971-1999)",
    "Best Modified Classic Car (1900-1970)",
    "Best Modified Stock Car (1971-1999)",
    "Best Modern Car or Truck (2000 or above)",
    "Best Classic Truck (Pre-2000)",
  ],
  bike: [
    "Best Motorcycles (All Years and Makes)",
  ],
};

// Generate year options from 1900 to 2026
export function getYearOptions(): number[] {
  const years: number[] = [];
  for (let y = 2026; y >= 1900; y--) {
    years.push(y);
  }
  return years;
}

// Fetch models for a specific make from NHTSA API
export async function fetchModelsForMake(make: string): Promise<string[]> {
  try {
    const res = await fetch(
      `https://vpic.nhtsa.dot.gov/api/vehicles/GetModelsForMake/${encodeURIComponent(
        make
      )}?format=json`
    );
    const data = await res.json();
    const models: string[] = data.Results.map(
      (r: { Model_Name: string }) => r.Model_Name
    )
      .filter((name: string) => name && name.trim().length > 0)
      .map((name: string) => name.trim())
      .sort((a: string, b: string) => a.localeCompare(b));
    return [...new Set(models)];
  } catch {
    return [];
  }
}

// Common motorcycle models by manufacturer
export const motorcycleModels: Record<string, string[]> = {
  "Harley-Davidson": [
    "Sportster",
    "Sportster S",
    "Sportster Iron 883",
    "Sportster Forty-Eight",
    "Street Glide",
    "Street Glide Special",
    "Road Glide",
    "Road Glide Special",
    "Road Glide Limited",
    "Road King",
    "Road King Special",
    "Electra Glide",
    "Ultra Limited",
    "Heritage Classic",
    "Fat Boy",
    "Fat Bob",
    "Breakout",
    "Low Rider",
    "Low Rider S",
    "Low Rider ST",
    "Street Bob",
    "Softail Standard",
    "Softail Slim",
    "Nightster",
    "Pan America",
    "LiveWire",
    "V-Rod",
    "Dyna",
    "Wide Glide",
    "Night Rod",
    "CVO",
    "Tri Glide Ultra",
    "Freewheeler",
    "Other",
  ],
  Honda: [
    "CBR600RR",
    "CBR1000RR",
    "CBR1000RR-R Fireblade",
    "CBR500R",
    "CBR300R",
    "CB650R",
    "CB500F",
    "CB300R",
    "CB1000R",
    "Gold Wing",
    "Africa Twin",
    "Rebel 300",
    "Rebel 500",
    "Rebel 1100",
    "Shadow",
    "Fury",
    "VTX",
    "Valkyrie",
    "NC750X",
    "CRF300L",
    "CRF450L",
    "Monkey",
    "Grom",
    "Trail 125",
    "Super Cub",
    "PCX",
    "Forza",
    "Other",
  ],
  Yamaha: [
    "YZF-R1",
    "YZF-R6",
    "YZF-R7",
    "YZF-R3",
    "MT-09",
    "MT-07",
    "MT-03",
    "MT-10",
    "XSR900",
    "XSR700",
    "VMAX",
    "V Star",
    "Bolt",
    "Tenere 700",
    "Super Tenere",
    "FJR1300",
    "Tracer 9 GT",
    "WR250R",
    "TW200",
    "XT250",
    "TMAX",
    "XMAX",
    "Star Venture",
    "Raider",
    "Stryker",
    "Other",
  ],
  Kawasaki: [
    "Ninja ZX-10R",
    "Ninja ZX-6R",
    "Ninja 650",
    "Ninja 400",
    "Ninja 300",
    "Ninja H2",
    "Z900",
    "Z650",
    "Z400",
    "Z900RS",
    "Versys 650",
    "Versys 1000",
    "Vulcan S",
    "Vulcan 900",
    "Vulcan 1700",
    "Concours 14",
    "KLR650",
    "KLX300",
    "W800",
    "Eliminator",
    "Other",
  ],
  Suzuki: [
    "GSX-R1000",
    "GSX-R750",
    "GSX-R600",
    "GSX-8S",
    "GSX-S1000",
    "GSX-S750",
    "Hayabusa",
    "SV650",
    "V-Strom 650",
    "V-Strom 1050",
    "Boulevard M109R",
    "Boulevard C50",
    "Boulevard S40",
    "DR-Z400",
    "DR650",
    "Katana",
    "Burgman",
    "Other",
  ],
  Ducati: [
    "Panigale V4",
    "Panigale V2",
    "Streetfighter V4",
    "Streetfighter V2",
    "Monster",
    "Multistrada V4",
    "Diavel V4",
    "Scrambler",
    "Scrambler Icon",
    "Scrambler Desert Sled",
    "Hypermotard 950",
    "SuperSport 950",
    "XDiavel",
    "DesertX",
    "Other",
  ],
  BMW: [
    "S 1000 RR",
    "S 1000 R",
    "S 1000 XR",
    "R 1250 GS",
    "R 1250 GS Adventure",
    "R 1250 RT",
    "R 1250 RS",
    "R nineT",
    "R 18",
    "R 18 Classic",
    "R 18 Transcontinental",
    "F 900 R",
    "F 900 XR",
    "F 850 GS",
    "F 750 GS",
    "G 310 R",
    "G 310 GS",
    "K 1600",
    "CE 04",
    "Other",
  ],
  Indian: [
    "Scout",
    "Scout Bobber",
    "Scout Rogue",
    "Chief",
    "Chief Bobber",
    "Chief Dark Horse",
    "Super Chief",
    "Chieftain",
    "Springfield",
    "Roadmaster",
    "Challenger",
    "Pursuit",
    "FTR",
    "FTR Rally",
    "Other",
  ],
  Triumph: [
    "Street Triple",
    "Speed Triple",
    "Tiger 900",
    "Tiger 1200",
    "Bonneville T120",
    "Bonneville T100",
    "Bonneville Bobber",
    "Bonneville Speedmaster",
    "Scrambler 900",
    "Scrambler 1200",
    "Thruxton",
    "Rocket 3",
    "Trident 660",
    "Speed 400",
    "Scrambler 400 X",
    "Daytona 660",
    "Other",
  ],
  KTM: [
    "390 Duke",
    "690 Duke",
    "790 Duke",
    "890 Duke",
    "1290 Super Duke R",
    "RC 390",
    "RC 8C",
    "390 Adventure",
    "890 Adventure",
    "1290 Super Adventure",
    "300 EXC",
    "450 SX-F",
    "Other",
  ],
  "Moto Guzzi": [
    "V7",
    "V85 TT",
    "V100 Mandello",
    "Stelvio",
    "California",
    "Eldorado",
    "Other",
  ],
  "Royal Enfield": [
    "Classic 350",
    "Meteor 350",
    "Hunter 350",
    "Continental GT 650",
    "Interceptor 650",
    "Himalayan",
    "Super Meteor 650",
    "Shotgun 650",
    "Other",
  ],
  "MV Agusta": [
    "F3",
    "Brutale",
    "Dragster",
    "Turismo Veloce",
    "Superveloce",
    "Lucky Explorer",
    "Other",
  ],
  Aprilia: [
    "RSV4",
    "RS 660",
    "Tuono V4",
    "Tuono 660",
    "Tuareg 660",
    "SR GT",
    "Other",
  ],
  Buell: [
    "XB12",
    "XB9",
    "1125R",
    "1125CR",
    "Blast",
    "Lightning",
    "Firebolt",
    "Ulysses",
    "Other",
  ],
  Victory: [
    "Cross Country",
    "Cross Roads",
    "Vegas",
    "Hammer",
    "Kingpin",
    "Vision",
    "Octane",
    "Magnum",
    "Other",
  ],
};

// Get motorcycle models for a given make
export function getMotorcycleModels(make: string): string[] {
  return motorcycleModels[make] || ["Other"];
}
